services:
  - type: web
    name: nexlab-java-app
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/your-app.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.jdk
